--- #YAML:1.0
name:               Rose-DBx-TestDB
version:            0.05
abstract:           test Rose::DB::Object modules
author:
    - Peter Karman <perl@peknet.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBD::SQLite:  1.08
    File::Temp:   0
    Rose::DB:     0
    Test::More:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
